SofterPawInsights/urls.py
from django.urls import path
from . import views


app_name = 'SofterPawInsights'
urlpatterns = [
    path('', views.index, name = "index"),
    path('simulation', views.simulation, name="simulation"),
    path('db', views.database, name='database'),
    path('<int:criteria_id>', views.detail, name="detail"),
    path('<int:criteria_id>/<slug:slug>', views.article, name="article")
]





SofterPawSpider/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name = "index")
    ]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from myproject import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    # path arguments are : route, view
    path('', views.home, name='home'),
    path('admin/', admin.site.urls),
    path('softerpawinsights/', include('SofterPawInsights.urls')),
    path('softerpawspider/', include('SofterPawSpider.urls'))
] 
urlpatterns += staticfiles_urlpatterns()

SofterPawInsights/models.py
from django.db import models

from django.utils.text import slugify
import uuid

# In this prototypical example,
# we use criteria to know what we are going to investigate in the 
# cloud data



class Criteria(models.Model):
    
    def __str__(self):
        return self.criteria_text

    criteria_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')


class Choice(models.Model):
    criteria = models.ForeignKey(Criteria, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)

class Article(models.Model):
    def __str__(self):
        return self.title
    criteria = models.ForeignKey(Criteria, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    # title = models.SlugField(max_length=200)
    slug = models.SlugField(unique=True, default=uuid.uuid1)
    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Article, self).save(*args, **kwargs)


class Performance(models.Model):
    keys = models.CharField(max_length=200, blank=True, null=True)
    clicks = models.CharField(max_length=200, blank=True, null=True)
    impressions = models.CharField(max_length=200, blank=True, null=True)
    ctr = models.CharField(max_length=200, blank=True, null=True)
    position = models.CharField(max_length=200, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'performance'

SofterPawSpider/models.py
from django.db import models

# Create your models here.

SofterPawInsights/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.template import loader
from django.http import Http404
from django.shortcuts import get_object_or_404
from django.contrib import messages

from .models import Criteria, Article, Performance


# Create your views here.

def index(request):
    latest_criteria_list = Criteria.objects.order_by('-pub_date')[:4]
    article_list = Article.objects.all()
    # article_list = Article.objects.filter(article__criteria = )

    context = {
        'latest_criteria_list': latest_criteria_list,
        'article_list': article_list,
    }

    # let's create an actual list that contains the articles that should be shown,
    # in the exact same order that should be in the index page.

    # I don't know how the fuck .objects.all() 'gets' the objects from the database
    # so ama do my own selection.

    # let's make a dirty test

    '''for p in Article.objects.raw('select id, criteria_id, title from SofterPawInsights_article'):
        print(p.criteria_id, p.title)'''

    return render(request, 'SofterPawInsights/index.html', context)


def detail(request, criteria_id):
    # this will get the actual object
    criteria = get_object_or_404(Criteria, pk=criteria_id)
    return render(request, 'SofterPawInsights/detail.html', {'criteria': criteria})


def article(request, slug, criteria_id):
    # variables in urls go here up, on function call

    # this needs to conform to the html call
    # article here is different from article in index.html

    # this will get a *list* of objects!
    article = Article.objects.filter(criteria__id=criteria_id, slug=slug)
    print(criteria_id, article)
    context = {
        'article': article,
    }
    return render(request, 'SofterPawInsights/article.html', context)


def simulation(request):
    latest_criteria_list = Criteria.objects.order_by('-pub_date')[:4]
    article_list = Article.objects.all()
    # article_list = Article.objects.filter(article__criteria = )

    context = {
        'latest_criteria_list': latest_criteria_list,
        'article_list': article_list,
    }

    # let's create an actual list that contains the articles that should be shown,
    # in the exact same order that should be in the index page.

    # I don't know how the fuck .objects.all() 'gets' the objects from the database
    # so ama do my own selection.

    # let's make a dirty test

    '''for p in Article.objects.raw('select id, criteria_id, title from SofterPawInsights_article'):
        print(p.criteria_id, p.title)'''

    return render(request, 'SofterPawInsights/simulation.html', context)


def database(request):
    all_items = Performance.objects.order_by('keys')
    all_fields = Performance._meta.get_fields()
    context = {
        'all_items': all_items,
        'all_fields': all_fields
    }

    from django.http import HttpResponseRedirect
    from django.urls import reverse
    if request.method == 'POST' and 'run_script' in request.POST:

        # import function to run
        from .querying.startupUpdate import Updater

        # call function
        _Updater = Updater()
        message = _Updater.update()

        # if table is already up to date, print nice error message to user
        if message != '':
            messages.add_message(request, messages.INFO, message)
            # context['error_message'] = message

        # return user to required page
        return HttpResponseRedirect(reverse('SofterPawInsights:database'))

    return render(request, 'SofterPawInsights/db.html', context)

SofterPawSpider/views.py
from django.shortcuts import render


def index(request):

    context = {}
    
    return render(request, 'SofterPawSpider/index.html', context)

myproject/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.template import loader
from django.http import Http404
from django.shortcuts import get_object_or_404





def home(request):

	context = {}
	
	
	return render(request, 'myproject/home.html', context)

SofterPawInsights/templates/SofterPawInsights/article.html
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
          crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static "SofterPawInsights/style.css" %}">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
            integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
            crossorigin="anonymous"></script>
    <script src="{% static "SofterPawInsights/script.js" %}"></script>

{% for article in article %}
    <h1> {{article.title}} </h1>
{% endfor %}

<p> 
    Results of the analysis per article will go here. 
</p>



SofterPawInsights/templates/SofterPawInsights/db.html
{% load static %}
{% load extras %}
<html>

<head>
    <meta name="google-site-verification" content="JenRw5wyE_cTqL7T2EeRo7LqhWh0PHWSVSTgw38pG1o" />

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
          crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static "SofterPawInsights/style.css" %}">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
            integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
            crossorigin="anonymous"></script>
    <script src="{% static "SofterPawInsights/script.js" %}"></script>
</head>


<body>
<h1>Check/Update the database</h1>

{% if messages %}
    <div class="messages">
        {% for message in messages %}
            {{ message }}
        {% endfor %}
    </div>
{% endif %}


<div class="row justify-content-center">
    <div class="col-auto">
      <table class="table table-responsive">
        <thead class="thead-dark">
            <tr>
                {% for column in all_fields %}
                <th>{{ column.name }}</th>
                {% endfor %}
            </tr>
        </thead>
        <tbody>
            {% for item in all_items %}
            <tr>
                {% for column in all_fields %}
                <td>  {{ item|get_attr:column.name }}  </td>
                {% endfor %}

            </tr>
            {% endfor %}
        </tbody>
    </table>
    </div>
  </div>





<div class="container">
  <div class="row">
    <div class="col text-center">
      <form method="post">
        {% csrf_token %}
        <button type="submit" name="run_script" class="btn btn-success" >Update</button>
    </form>
        <div class="spinner-border" role="status">
            <span class="sr-only">Loading...</span>
        </div>
    </div>
  </div>
</div>


</body>



</html>

SofterPawInsights/templates/SofterPawInsights/detail.html
{% load static %}
{% load extras %}
<html>

<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
          crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static "SofterPawInsights/style.css" %}">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
            integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
            crossorigin="anonymous"></script>
    <script src="{% static "SofterPawInsights/script.js" %}"></script>
</head>


<h1>{{ criteria.criteria_text }}</h1>
<ul>
{% for choice in criteria.choice_set.all %}
    <li>{{ choice.choice_text }}</li>
{% endfor %}
</ul>
</html>

SofterPawInsights/templates/SofterPawInsights/index.html
{% load static %}
{% load extras %}
<html>
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
          crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static "SofterPawInsights/style.css" %}">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
            integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
            crossorigin="anonymous"></script>
    <script src="{% static "SofterPawInsights/script.js" %}"></script>

</head>
<body>
<h1>Welcome to SofterPawInsights!</h1>
        <div class="container">
  <div class="row">
        <div class="col" >

<p>Here, we will be able to identify and predict which content drives us the best results in terms of traffic, CTR, Amazon
    conversions ... </p>


<p>Here is what you can do:</p>

<a href="db" >Check/Update the database</a>


        </div>
        </div>
        </div>

</body>


</html>


SofterPawInsights/templates/SofterPawInsights/simulation.html
<p>Below is a simulated list of how the system would yield the target articles that belong to a specific 
    research criteria.
</p>
{% if latest_criteria_list %}
    <ul>
    {% for criteria in latest_criteria_list %}
        <li><a href= "{% url 'detail' criteria.id %}" >{{ criteria.criteria_text }}</a></li>
            <ul>
            {% for article in article_list %}
                {% if article.criteria == criteria %}
                <li><a href="/softerpawinsights/{{ article.criteria_id }}/{{ article.slug }}">{{ article.title }}</a></li>
                {% endif %}
            {% endfor %}
            </ul>
    {% endfor %}
    </ul>
{% else %}
    <p>No criterias are available.</p>
{% endif %}

SofterPawSpider/templates/SofterPawSpider/index.html
<p>Under construction ... </p>

myproject/templates/myproject/home.html
{% load static %}
{% load extras %}
<html>
<head>
    <meta name="google-site-verification" content="JenRw5wyE_cTqL7T2EeRo7LqhWh0PHWSVSTgw38pG1o" />

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
          crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static "SofterPawInsights/style.css" %}">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
            integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
            crossorigin="anonymous"></script>
    <script src="{% static "SofterPawInsights/script.js" %}"></script>
</head>
<h1> Welcome to SofterpawIntel!</h1>

<div class="container">
  <div class="row">
        <div class="col" >

        This project combines :
<ul>
    <li>SofterpawInsights (google console API)</li>
    <ul>
        <li>Simple data browser</li>
        <li>AI insights maker</li>
    </ul>
    <li>SofterpawSpider (simple crawler)</li>
</ul>

<h2><a href="/softerpawinsights/" >SofterpawInsights</a></h2>

<h3>Motivation</h3>

We want to be able to pull data from our search console that is directly linked to our affiliate marketing blog.

We also want to be able to generate insights for some <i>key</i> questions.

<h4>Examples of questions we might want to consider:</h4>
<ul>
    <li>Which posts ( -> categories) drove the most impressions in the last X weeks?</li>
</ul>

<h4>More advanced:</h4>

<ul>
    <li>Which posts were the 'fastest' in terms of ranking up in Google?</li>
</ul>

<h4>And towards a web app, sort of</h4>

Afterwards, we want to build an "AI" system, capable of "choosing" and telling us:

<ul>
    <li>Which category to choose</li>
    <li>and/or what should our next article be about</li>
</ul>

We can build that as a "web app", full stack, and make it available to front end usage, input being which question to select, and output being the predicted category/cluster of keywords to write the next article about.

<h2><a href="/softerpawspider/" >SofterpawSpider</a></h2>

We would like to see our own simple web crawler that pulls keywords that we need for our content to rank, using maching learning models.

        </div>
        </div>
        </div>

</html>